version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: organization_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: ../containers/api/Dockerfile
    container_name: organization_api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "npm run migrate:up && npm run start:dev"
    volumes:
      - ./api:/usr/src/app 
      - /usr/src/app/node_modules 
      - ./api/uploads:/usr/src/app/uploads 
    
  app:
    build:
      context: ./app
      dockerfile: ../containers/app/Dockerfile
    container_name: hr_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: